# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  SanityCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        run: npm run deploy:beta
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PAYMENT_ACCESS_TOKEN_DRCG_PROPERTIES: ${{ secrets.PAYMENT_ACCESS_TOKEN_DRCG_PROPERTIES }}
          PAYMENT_ACCESS_TOKEN_EB_SOLUTIONS: ${{ secrets.PAYMENT_ACCESS_TOKEN_EB_SOLUTIONS }}
